### ISSUE TITLE
Tray icon not available

### ISSUE THREAD

**Issue by viveknk** [yuki792/NeighborNote#6]
Installed and running NeighborNote on 64-bit Ubuntu (12.04 LTS)

All works great!! But, On choosing "minimizeOnClose=true" option in settings, the tray icon must be added. But no tray icon is present. And, when minimized, the neighbornote window closes but the processes run on background..

No tray icon, so could not get the window to front again. Had to kill the processes and open the app again.

Is there a way to add it in tray? or any command to bring it to front?

**Comment by yuki792** [comment]
It works well on my Linux Mint 17, but certainly it doesn't work on Ubuntu12.04 (and 14.04) as you said.

As far as I searched, this is caused by Unity's limitation.
Unity prohibits individual applications using system tray.

The workaround is following.
1. Install dconf-editor.  `sudo apt-get install dconf-editor`
2. Open dconf-editor, navigate to desktop > unity > panel > systray-whitelist.
3. Remove value and type *['all']* in its place.
4. Log out and log back in for the changes to take effect. 

> **TIP** On Ubuntu 14.04, navigate to com > canonical > unity-gtk-module > whitelist.

Regards,

**Comment by viveknk** [comment]
Yeah. I tried that way only. Now it is fine. But, i have some issues in sync. I will open a new ticket for it.
